import { Component, signal } from '@angular/core';

@Component({
  selector: 'app-faq',
  imports: [],
  templateUrl: './faq.html',
  styleUrl: './faq.scss',
})
export class Faq {

  // Track which item is open
  activeId = signal<number | null>(null);

  // Your Product-Focused FAQ Data
  faqItems = [
    {
      id: 1,
      question: "How do I start building with UiMolder?",
      answer: "Simply launch the 'Forge' builder. You can start with our structural blueprints or a blank canvas. Our recursive engine allows you to nest components infinitely, while the Signal Engine handles all state logic automatically in the background."
    },
    {
      id: 2,
      question: "What is the 'Recursive Power' feature?",
      answer: "It's our secret sauce. The Recursive Power allows you to create components that can contain instances of themselves, enabling infinite nesting and complex hierarchies without any performance degradation."
    },
    {
      id: 3,
      question: "Can I customize the 'Recursive Power' nesting levels?",
      answer: "Absolutely. Our engine is built for infinite structural nesting. The system protocol allows you to scale component complexity without sacrificing render speed."
    },
    {
      id: 4,
      question: "What makes UiMolder different from other UI builders?",
      answer: "Unlike traditional 'drag-and-drop' tools that generate bloated code, UiMolder is built on Angular 20 Signals. This means your output is natively 'Zoneless,' incredibly fast, and follows high-performance architectural patterns by default."
    },
    {
      id: 5,
      question: "Is UiMolder suitable for enterprise applications?",
      answer: "Yes. UiMolder's architecture is designed to handle complex, large-scale applications with ease. The Recursive Power and Signal Engine ensure that even the most intricate UIs remain performant and maintainable."
    },
    {
      id: 6,
      question: "Can I export the code generated by UiMolder?",
      answer: "Yes, you can export clean, production-ready Angular code that is free of any framework-specific dependencies. This allows for maximum flexibility and portability across different projects and platforms."
    },
    {
      id: 7,
      question: "What are the core advantages of the Recursive Power system?",
      answer: "The primary advantage is 'Architecture as a Service.' Instead of building static pages, you are building self-evolving systems. When you update a parent blueprint, the recursive logic propagates those changes throughout your entire application instantly."
    },
    {
      id: 8,
      question: "What exactly do I get after completing a build?",
      answer: "You get a production-ready, highly optimized Angular 20 project. You can choose to download the clean source code."
    },
    {
      id: 9,
      question: "Is there a learning curve for the Signal Engine?",
      answer: "Zero. While the tech is advanced, the UI is intuitive. You work with visual signals, and the engine writes the reactive code. It’s designed to give junior developers senior-level architectural power."
    },
    {
      id: 10,
      question: "Is the Adaptive Type System truly fluid?",
      answer: "Yes. It uses 'Fluid by Default' logic to intelligently reshape typography and grids across all device breakpoints without layout shift."
    }
  ];

  toggle(id: number) {
    this.activeId.update(val => val === id ? null : id);
  }

}
